license:
  # 是否调试模式
  dev-model: false
  # 是否启用授权校验工具
  enable: true
  # 本地公钥路径
  public-key-path: "public.key"
  # 授权管理器路径
  license-path: "license.lic"
  # 是否开启定时任务自动刷新
  enableAutoRefresh: true
  # 是否启用拦截器
  enableInterceptor: true
